packages:
  - .
  - ui
  - extensions/*

onlyBuiltDependencies:
  - '@whiskeysockets/baileys'
  - '@lydell/node-pty'
  - '@matrix-org/matrix-sdk-crypto-nodejs'
  - authenticate-pam
  - better-sqlite3
  - esbuild
  - protobufjs
  - sharp
